CREATE TABLE PARTICIPANT (
 Id_Participant INT(5) PRIMARY KEY AUTO_INCREMENT,
 FirstName VARCHAR(15) NOT NULL,
 LastName VARCHAR(15) NOT NULL,
 Email VARCHAR(30) NOT NULL,
 Phone NUMERIC(12),
 PasswordParticipant VARCHAR(20) NOT NULL,
 NomeCompany VARCHAR(15) NOT NULL,
 PositionJob VARCHAR(15) NOT NULL,
 CodeEvent INT (5)
 
);

ALTER TABLE PARTICIPANT ADD CONSTRAINT `fk_participate` FOREIGN KEY(CodeEvent) REFERENCES EVENTSUNIQUE(IdEvent);

CREATE TABLE EVENTSUNIQUE (
 IdEvent INT (5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
 RegisterParticipant BOOLEAN NOT NULL,
 CompanyEvent VARCHAR (20) NOT NULL,
 IdPart INT(5) /* Participante Escolhe versão (chave estrangeira/versão)*/
 
);

ALTER TABLE EVENTSUNIQUE ADD CONSTRAINT `fk_ParticipantEvent` FOREIGN KEY (IdPart) REFERENCES VERSION(VersionId);

CREATE TABLE VERSION (
  VersionId INT (5) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ChooseVersion INT (5)
);

ALTER TABLE VERSION ADD CONSTRAINT `fk_choose` FOREIGN KEY (ChooseVersion) REFERENCES DESKTOP(IdDesktop);
ALTER TABLE VERSION ADD CONSTRAINT `fk_chooseVR` FOREIGN KEY (ChooseVersion) REFERENCES VR (IdVR);


CREATE TABLE DESKTOP (
  HeChose BOOLEAN,
  IdDesktop INT(5) PRIMARY KEY AUTO_INCREMENT
  
);

CREATE TABLE VR (
   HeChose BOOLEAN,
   IdVR INT(5) PRIMARY KEY AUTO_INCREMENT,
   Regulation VARCHAR(250) NOT NULL,
   CodeAddress INT (5)
);

ALTER TABLE VR ADD CONSTRAINT `fk_lives` FOREIGN KEY (CodeAddress) REFERENCES ADDRESS (IdAddress); 

CREATE TABLE ADDRESS (
   StreetName VARCHAR(15) NOT NULL,
   NumberHouse INT(5) NOT NULL,
   Municipality VARCHAR(25) NOT NULL,
   Country VARCHAR(15) NOT NULL,
   ZipCode INT(8) NOT NULL,
   IdAddress INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL
   
);




